@startuml
enum DataStruct.SupplyType {
+  MO
+  MRP
+  PLAN
+  PO
+  PR
+  SO
}

abstract class DataStruct.Labeled {
- String id
}

class DataStruct.Resource.UnlimitedResource {
}
class DataStruct.TimeSlot {
- String shiftID
- float start
- float end
}

class DataStruct.Resource.RenewableResource {
- int capacity
- List<TimeSlot> timeSlots
}

enum DataStruct.TaskType {
+  PARENT
+  CHILD
}

enum DataStruct.ProductionMethod {
+  SELF
+  OUTSOURCING
}

class DataStruct.Task {
- String materialId
- String materialDescription
- float Quantity
- List<Operation> craftPath
- List<MasterDemand> masterDemands
- SupplyType supplyType
- float earliestStartTime
- float latestStartTime
- float materialSetTime
}

class DataStruct.MasterDemand {
- float requiredDate
- float deliveryDate
- float breachDate
- float promisedDate
- float prePromisedDate
}

class DataStruct.Operation {
- String name
- int order
- List<R> availableResources
- Task parentTask
- List<Operation> previousOperations
- List<Operation> nextOperations
- ProductionMethod productionMethod
- float resourceOccupiedPostTime
- float NonResourceOccupiedPostTime
- boolean isLocked
- int plannedStartTime
- int plannedEndTime
- RenewableResource plannedResource
- boolean isFirst
- boolean isLast
}

class DataStruct.Resource.ResourceRequirement {
- AmountLimitedResource amountLimitedResource
- RenewableResource renewableResource
- UnlimitedResource unlimitedResource
}

class DataStruct.Resource.AmountLimitedResource {
- float amount
}

abstract class DataStruct.Resource.ResourceBase {
- String name
- String resourceGroup
- String productionLine
}



DataStruct.Resource.ResourceBase <|-- DataStruct.Resource.UnlimitedResource
DataStruct.Resource.ResourceBase <|-- DataStruct.Resource.RenewableResource
DataStruct.Labeled <|-- DataStruct.Task
DataStruct.Labeled <|-- DataStruct.MasterDemand
DataStruct.Labeled <|-- DataStruct.Operation
DataStruct.Labeled <|-- DataStruct.Resource.ResourceRequirement
DataStruct.Resource.ResourceBase <|-- DataStruct.Resource.AmountLimitedResource
DataStruct.Labeled <|-- DataStruct.Resource.ResourceBase
@enduml